# Generated by Django 6.0.2 on 2026-02-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
